create extension if not exists pgcrypto;

create table if not exists public.fake_ads (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  button text not null,
  category text not null,
  size text not null check (size in ('small', 'medium', 'large')),
  effect text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fake_ads_active_id_idx
  on public.fake_ads (is_active, id);

alter table public.fake_ads enable row level security;

drop policy if exists "Public can read active fake ads" on public.fake_ads;
create policy "Public can read active fake ads"
  on public.fake_ads
  for select
  using (is_active = true);

create or replace function public.touch_fake_ads_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists fake_ads_updated_at on public.fake_ads;
create trigger fake_ads_updated_at
before update on public.fake_ads
for each row execute function public.touch_fake_ads_updated_at();

-- Deterministic seed: exactly 1,000 ads, with 50 handcrafted animation effects reused as
-- interaction themes while every database row gets its own copy, title and text.
truncate table public.fake_ads restart identity;

with source as (
  select
    n,
    (array[
      'productivity','lottery','pencil','ram','cat','nothing-subscription','premium-air','zero-cost','ad-social','sleep',
      'rock','computer-scan','celebrity','premium-nothing','stop-scroll','internet-misses','rich','meta-ad','second-internet','celebration',
      'wifi','millionaire','chair','speed','mouse','ai','height','pixel','unlock','secret',
      'button','free-nothing','oxygen','busy','ceo','weird-trick','surprise','insurance','guaranteed-nothing','rectangle',
      'browser','reality','tabs','money-generator','premium-plus','stop-ads','millionth','download-internet','absolute-nothing','final'
    ])[((n - 1) % 50) + 1] as effect,
    (array[
      'productivity','prize','shopping','technology','animals','subscription','luxury','meta','social','lifestyle',
      'shopping','technology','social','premium','meta','meta','money','meta','technology','meta',
      'technology','money','shopping','technology','technology','technology','lifestyle','technology','meta','secret',
      'meta','shopping','luxury','productivity','business','clickbait','mystery','business','meta','shopping',
      'technology','technology','technology','money','premium','meta','prize','technology','meta','meta'
    ])[((n - 1) % 50) + 1] as category,
    (array['small','medium','large'])[((n - 1) % 3) + 1] as size,
    (array[
      'BECOME RIDICULOUSLY PRODUCTIVE','CLAIM A SUSPICIOUS PRIZE','BUY SOMETHING YOU DIDN’T KNOW EXISTED','UPGRADE YOUR INTERNET LIFE','YOUR PET HAS A MESSAGE',
      'SUBSCRIBE TO ABSOLUTELY NOTHING','PREMIUM AIR IS BACK','THIS AD COSTS NOTHING','MEET THE OTHER THREE PEOPLE','FIX YOUR ENTIRE LIFE',
      'BUY A ROCK BUT FASTER','YOUR COMPUTER IS DEFINITELY FINE','BECOME INTERNET FAMOUS','UPGRADE NOTHING PREMIUM','STOP SCROLLING RIGHT NOW',
      'THE INTERNET NEEDS YOU','BECOME RICHER THAN YESTERDAY','YOU ARE LOOKING AT AN AD','BUY ANOTHER INTERNET','CONGRATULATIONS, ANOTHER AD',
      'FREE WI-FI MAYBE','BECOME A MILLIONAIRE EVENTUALLY','SIT ON NOTHING','MAKE YOUR INTERNET 200% FASTER','YOUR MOUSE DESERVES A BREAK',
      'ASK AN AI THAT KNOWS NOTHING','BECOME 12% TALLER','CLAIM ONE DIGITAL PIXEL','UNLOCK ABSOLUTELY EVERYTHING','YOU FOUND THE SECRET AD',
      'CLICK THE BEST BUTTON','CLAIM FREE NOTHING','BREATHE PREMIUM OXYGEN','LOOK EXTREMELY BUSY','BECOME A COMPLETELY UNOFFICIAL CEO',
      'ONE WEIRD TRICK ACTUALLY','CLICK FOR A SURPRISE','GET INSURANCE AGAINST NOTHING','100% GUARANTEED NOTHING','OWN THIS RECTANGLE',
      'YOUR BROWSER WANTS A SNACK','UPGRADE YOUR REALITY','GET MORE TABS','GENERATE FREE €0.00','ADVERTISEMENT PREMIUM PLUS',
      'STOP ADS FOR 0.00 SECONDS','YOU ARE DEFINITELY THE MILLIONTH VISITOR','DOWNLOAD THE INTERNET','ABSOLUTELY NOTHING','THE FINAL AD MAYBE'
    ])[((n - 1) % 50) + 1] as title_base,
    (array[
      'A revolutionary system that promises results and delivers mostly confidence.',
      'Congratulations! The exact details are unavailable, but the button looks trustworthy.',
      'A product so unnecessary that you’ll wonder why it exists.',
      'Your device has requested an entirely questionable upgrade.',
      'Something important has happened to your pet. Probably.',
      'Receive a perfectly empty experience directly to your inbox.',
      'The luxury version of something you already get for free.',
      'An advertisement with a surprisingly low production budget.',
      'There are probably people out there who share this interest.',
      'A lifestyle solution nobody asked for but somebody advertised.',
      'A premium object with a suspiciously simple business model.',
      'Everything is fine. We checked approximately one thing.',
      'A fast route to becoming famous for no particular reason.',
      'Premium benefits include fewer benefits than the normal version.',
      'A serious request from an advertisement that takes itself too seriously.',
      'The internet has noticed your absence and would like to discuss it.',
      'Financial advice delivered by a completely imaginary company.',
      'Meta enough to be an advertisement about advertisements.',
      'The extra internet you never knew you needed.',
      'Congratulations on continuing to interact with advertisements.',
      'A password that may or may not work somewhere nearby.',
      'A mathematical shortcut to wealth that ends exactly where you expect.',
      'Furniture technology has reached a completely unnecessary milestone.',
      'A speed claim assembled with confidence rather than evidence.',
      'Your pointing device has completed another heroic day of clicking.',
      'Artificial intelligence has never been this gloriously unhelpful.',
      'A life-changing transformation with no known mechanism.',
      'A tiny digital object that definitely matters now.',
      'The website may or may not have been locked until you clicked.',
      'You discovered an advertisement nobody was supposed to discover.',
      'One button. Infinite importance. Absolutely no supporting evidence.',
      'A free quantity of nothing with zero shipping costs.',
      'Exactly the same air, now presented as a luxury product.',
      'A productivity strategy designed to look extremely productive.',
      'Corporate advancement without the awkward part where you need qualifications.',
      'A weird trick with a weird amount of confidence.',
      'A surprise with absolutely no spoiler protection.',
      'Protection from a problem that was invented for this advertisement.',
      'A guarantee so strong that it guarantees nothing at all.',
      'Modern ownership has entered its most rectangular era.',
      'Even your browser deserves snacks occasionally.',
      'Reality has finally received a software update request.',
      'Open enough tabs and eventually one of them becomes meaningful.',
      'A money generator that respects the concept of zero.',
      'More premium advertising for people who already have advertisements.',
      'A temporary ad-free experience lasting approximately no time.',
      'A suspicious visitor milestone with suspiciously convenient timing.',
      'The whole internet. One download. Totally practical.',
      'There is nothing here. We checked twice.',
      'The final advertisement. Unless there is another one.'
    ])[((n - 1) % 50) + 1] as description_base,
    (array[
      'LEARN MORE','CLAIM NOW','SHOP NOW','UPGRADE','VIEW OFFER','SUBSCRIBE','BUY AIR','CONTINUE','MEET THEM','FIX IT',
      'BUY ROCK','SCAN NOW','BECOME FAMOUS','UPGRADE','KEEP SCROLLING','RETURN','START','OK','GET INTERNET','CELEBRATE',
      'GET PASSWORD','CALCULATE','BUY CHAIR','TEST SPEED','REST MOUSE','ASK AI','GET TALLER','CLAIM PIXEL','UNLOCK','OPEN SECRET',
      'CLICK BUTTON','CLAIM NOTHING','BREATHE PREMIUM','LOOK BUSY','BECOME CEO','SEE TRICK','SURPRISE ME','GET COVER','GUARANTEE IT','BUY RECTANGLE',
      'FEED BROWSER','UPGRADE','GET TABS','GENERATE MONEY','UPGRADE','STOP ADS','CELEBRATE','DOWNLOAD','DO NOTHING','THE END'
    ])[((n - 1) % 50) + 1] as button
  from generate_series(1, 1000) as g(n)
)
insert into public.fake_ads (id, title, description, button, category, size, effect)
select
  n,
  title_base || ' #' || n,
  description_base || ' Edition ' || n || '.',
  button,
  category,
  size,
  effect
from source;

select count(*) as seeded_ads from public.fake_ads;
